AllCops:
  Exclude:
    - 'db/schema.rb'
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Style/Documentation:
  Enabled: false
Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'
