swagger: '2.0'
info:
  title: TodoList API
  description: |
    This is a documentation of TodoList API.

    To use API you need to use Bearer token authentication, obtain a token at /auth/login path.
  version: "1.0.0"
basePath: /api/v1
produces:
  - application/json
securityDefinitions:
  authorizationHeader:
    type: apiKey
    in: header
    name: authorization
security:
  - authorizationHeader: []
paths:
  /lists:
    get:
      summary: Fetch all lists
      description: Fetches all the lists existing in the database
      tags:
        - Lists
      responses:
        200:
          description: An array of lists
          schema:
            type: array
            items:
              $ref: '#/definitions/List'
    post:
      summary: Create new list
      description: Creates new list with attributes specified in request body
      tags:
        - Lists
      parameters:
        - in: body
          name: list
          description: The list to create
          schema:
            type: object
            required:
              - title
            properties:
              title:
                type: string
              deadline:
                type: string
      responses:
        200:
          description: List object
          schema:
            type: object
            $ref: '#/definitions/List'
        422:
          description: Unprocessable entity,
            list could not be created due to invalid attributes
  /lists/{listId}:
    get:
      summary: Fetch list of given ID
      description: Fetches only the list which ID matches param ID
      tags:
        - Lists
      parameters:
        - in: path
          name: listId
          schema:
            type: integer
          required: true
          description: Numeric ID of the list to get
      responses:
        200:
          description: List object
          schema:
            type: object
            $ref: '#/definitions/List'
        404:
          description: List of given ID not found
          schema:
            type: object
            $ref: '#/definitions/Error'
    put:
      summary: Update a list
      description: Updates a list of given ID with attributes
        specified in request body
      tags:
        - Lists
      parameters:
        - in: path
          name: listId
          schema:
            type: integer
          required: true
          description: Numeric ID of the list to update
        - in: body
          name: list
          description: The new list attributes
          schema:
            type: object
            required:
              - title
            properties:
              title:
                type: string
              deadline:
                type: string
      responses:
        200:
          description: List object
          schema:
            type: object
            $ref: '#/definitions/List'
        422:
          description: Unprocessable entity,
            list could not be created due to invalid attributes
        404:
          description: List of given ID not found
          schema:
            type: object
            $ref: '#/definitions/Error'
    delete:
      summary: Deletes list of given ID
      description: Deletes the list which ID matches param ID from database
      tags:
        - Lists
      parameters:
        - in: path
          name: listId
          schema:
            type: integer
          required: true
          description: Numeric ID of the list to delete
      responses:
        204:
          description: The list has been deleted succesfully
        404:
          description: List of given ID not found
          schema:
            type: object
            $ref: '#/definitions/Error'
  /notes:
    get:
      summary: Fetch all notes
      description: Fetches all the notes existing in the database
      tags:
        - Notes
      responses:
        200:
          description: An array of notes
          schema:
            type: array
            items:
              $ref: '#/definitions/Note'
    post:
      summary: Create new note
      description: Creates new note with attributes specified in request body
      tags:
        - Notes
      parameters:
        - in: body
          name: note
          description: The note to create
          schema:
            type: object
            required:
              - title
            properties:
              title:
                type: string
              content:
                type: string
              list_id:
                type: string
      responses:
        200:
          description: Note object
          schema:
            type: object
            $ref: '#/definitions/Note'
        422:
          description: Unprocessable entity,
            note could not be created due to invalid attributes
  /notes/{noteId}:
    get:
      summary: Fetch note of given ID
      description: Fetches only the note which ID matches param ID
      tags:
        - Notes
      parameters:
        - in: path
          name: noteId
          schema:
            type: integer
          required: true
          description: Numeric ID of the note to get
      responses:
        200:
          description: Note object
          schema:
            type: object
            $ref: '#/definitions/Note'
        404:
          description: Note of given ID not found
          schema:
            type: object
            $ref: '#/definitions/Error'
    put:
      summary: Update a note
      description: Updates a note of given ID with attributes
        specified in request body
      tags:
        - Notes
      parameters:
        - in: path
          name: noteId
          schema:
            type: integer
          required: true
          description: Numeric ID of the note to update
        - in: body
          name: note
          description: The new note attributes
          schema:
            type: object
            required:
              - title
            properties:
              title:
                type: string
              content:
                type: string
              list_id:
                type: string
      responses:
        200:
          description: Note object
          schema:
            type: object
            $ref: '#/definitions/Note'
        422:
          description: Unprocessable entity,
            note could not be created due to invalid attributes
        404:
          description: Note of given ID not found
          schema:
            type: object
            $ref: '#/definitions/Error'
    delete:
      summary: Deletes note of given ID
      description: Deletes the note which ID matches param ID from database
      tags:
        - Notes
      parameters:
        - in: path
          name: noteId
          schema:
            type: integer
          required: true
          description: Numeric ID of the note to delete
      responses:
        204:
          description: The note has been deleted succesfully
        404:
          description: Note of given ID not found
          schema:
            type: object
            $ref: '#/definitions/Error'
definitions:
  List:
    $ref: 'definitions/list.yaml'
  Note:
    $ref: 'definitions/note.yaml'
  Error:
    $ref: 'definitions/error.yaml'
