admin:
  password: password
  username: admin
auth0:
  api_audience: https://todolist-api.dev
  client_id: 3oemZRlPfY4PcWe27lG4IxccBpL5eGen
  client_secret: 4smJMxsrSdC8ft6U6K06ZcJPVskPDNvbjsZl0FYkt9-iu4XdUwUY0zvLfzgVDUty
  domain: todolist-dev.eu.auth0.com
hostname: http://todolist.local:3000
mailer:
  from: mailer@todolist.dev
secret_key_base: 95b1277ac98d63dda2377172098e8213349c73538ed8fd8d2ab31c5c5087724ca60c4a1331932451550347b5fbae25cc49166eea042d212759f262f8d60ff9e8
