admin_password: <%= ENV.fetch 'ADMIN_PASSWORD' %>
admin_username: <%= ENV.fetch 'ADMIN_USERNAME' %>
app_env: <%= ENV.fetch 'APP_ENV' %>
auth0_api_audience: <%= ENV.fetch 'AUTH0_API_AUDIENCE' %>
auth0_client_id: <%= ENV.fetch 'AUTH0_CLIENT_ID' %>
auth0_client_secret: <%= ENV.fetch 'AUTH0_CLIENT_SECRET' %>
auth0_domain: <%= ENV.fetch 'AUTH0_DOMAIN' %>
database_url: <%= ENV.fetch 'DATABASE_URL' %>
raven_dsn: <%= ENV.fetch 'RAVEN_DSN' %>
secret_key_base: <%= ENV.fetch 'SECRET_KEY_BASE' %>
