admin:
  password: <%= ENV.fetch 'ADMIN_PASSWORD' %>
  username: <%= ENV.fetch 'ADMIN_USERNAME' %>
app_env: <%= ENV.fetch 'APP_ENV' %>
auth0:
  api_audience: <%= ENV.fetch 'AUTH0_API_AUDIENCE' %>
  client_id: <%= ENV.fetch 'AUTH0_CLIENT_ID' %>
  client_secret: <%= ENV.fetch 'AUTH0_CLIENT_SECRET' %>
  domain: <%= ENV.fetch 'AUTH0_DOMAIN' %>
database_url: <%= ENV.fetch 'DATABASE_URL' %>
heroku:
  api_token: <%= ENV.fetch 'HEROKU_API_TOKEN' %>
  app_name: <%= ENV.fetch 'HEROKU_APP_NAME' %>
hostname: <%= ENV.fetch 'HOSTNAME' %>
raven_dsn: <%= ENV.fetch 'RAVEN_DSN' %>
secret_key_base: <%= ENV.fetch 'SECRET_KEY_BASE' %>
